-- MySQL Script generated by MySQL Workbench
-- Thu May  8 10:05:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tarjeta` (
  `IdTarjeta` INT NOT NULL AUTO_INCREMENT,
  `Numero_Tarjeta` VARCHAR(16) NOT NULL,
  `CVV` INT(4) NOT NULL,
  `Fecha_Venc` DATE NOT NULL,
  PRIMARY KEY (`IdTarjeta`))
ENGINE = InnoDB;

INSERT INTO mydb.Tarjeta (IdTarjeta, Numero_Tarjeta, CVV, Fecha_Venc)
VALUES 
(1, 1111222233334444, 456, '2026-05-30'),
(2, 1111222233333698, 210, '2027-02-12');


-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `IdRol` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdRol`))
ENGINE = InnoDB;

INSERT INTO mydb.Rol (IdRol, Nombre)
VALUES 
('1','Cliente'),
('2','Administrador');



-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Fecha_Nacimiento` DATE NULL,
  `Correo` VARCHAR(30) NOT NULL,
  `Contra` VARCHAR(45) NOT NULL,
  `URL_Foto_perf` VARCHAR(255) NULL,
  `IdTarjeta` INT NOT NULL,
  `IdRol` INT NOT NULL,
  PRIMARY KEY (`IdUsuario`),
  CONSTRAINT `fk_Usuario_Tarjeta1`
    FOREIGN KEY (`IdTarjeta`)
    REFERENCES `mydb`.`Tarjeta` (`IdTarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`IdRol`)
    REFERENCES `mydb`.`Rol` (`IdRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Correo_UNIQUE` ON `mydb`.`Usuario` (`Correo` ASC) VISIBLE;

CREATE INDEX `fk_Usuario_Tarjeta1_idx` ON `mydb`.`Usuario` (`IdTarjeta` ASC) VISIBLE;

CREATE INDEX `fk_Usuario_Rol1_idx` ON `mydb`.`Usuario` (`IdRol` ASC) VISIBLE;

INSERT INTO mydb.Usuario 
(IdUsuario,Nombre, Fecha_Nacimiento, Correo, Contra, URL_Foto_perf, IdTarjeta, IdRol)
VALUES 
('1','Gael Colunga', '2005-07-27', 'gael@ejempl0.com', '123', NULL, 1, 1),
('2','Jesus Ortega', '2004-05-15', 'jesus@ejempl0.com', '456', NULL, 2, 2);


-- -----------------------------------------------------
-- Table `mydb`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal` (
  `IdSucursal` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(255) NOT NULL,
  `IdUsuario` INT NOT NULL,
  PRIMARY KEY (`IdSucursal`),
  CONSTRAINT `fk_Sucursal_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `mydb`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Sucursal_Usuario1_idx` ON `mydb`.`Sucursal` (`IdUsuario` ASC) VISIBLE;

INSERT INTO mydb.Sucursal (IdSucursal, Nombre, Direccion, IdUsuario)
VALUES ('1','Sucursal Centro', 'Calle Reforma #123, CDMX', 2);



-- -----------------------------------------------------
-- Table `mydb`.`Plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Plan` (
  `IdPlan` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Precio` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`IdPlan`))
ENGINE = InnoDB;

INSERT INTO mydb.Plan (IdPlan ,Nombre, Precio)
VALUES ('1','Plan Premium', '299.99');


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;

INSERT INTO mydb.Estado (IdEstado, Tipo_Estado)
VALUES 
('1', 'Activo'),
('2', 'Pendiente'),
('3', 'Cancelado');

-- -----------------------------------------------------
-- Table `mydb`.`Suscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Suscripcion` (
  `IdSuscripcion` INT NOT NULL AUTO_INCREMENT,
  `Fecha_inicio` DATE NOT NULL,
  `Fecha_fin` DATE NOT NULL,
  `IdUsuario` INT NOT NULL,
  `IdPlan` INT NOT NULL,
  `IdEstado` INT NOT NULL,
  PRIMARY KEY (`IdSuscripcion`),
  CONSTRAINT `fk_Suscripcion_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `mydb`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suscripcion_Plan1`
    FOREIGN KEY (`IdPlan`)
    REFERENCES `mydb`.`Plan` (`IdPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suscripcion_Estado1`
    FOREIGN KEY (`IdEstado`)
    REFERENCES `mydb`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Suscripcion_Usuario1_idx` ON `mydb`.`Suscripcion` (`IdUsuario` ASC) VISIBLE;

CREATE INDEX `fk_Suscripcion_Plan1_idx` ON `mydb`.`Suscripcion` (`IdPlan` ASC) VISIBLE;

CREATE INDEX `fk_Suscripcion_Estado1_idx` ON `mydb`.`Suscripcion` (`IdEstado` ASC) VISIBLE;

INSERT INTO mydb.Suscripcion 
(IdSuscripcion, Fecha_inicio, Fecha_fin, IdUsuario, IdPlan, IdEstado)
VALUES 
('1' ,'2025-05-22', '2025-11-22', 1, 1, 1);


-- -----------------------------------------------------
-- Table `mydb`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pago` (
  `IdPago` INT NOT NULL AUTO_INCREMENT,
  `Fecha_pago` DATE NOT NULL,
  `Monto` DECIMAL(10,2) NOT NULL,
  `IdUsuario` INT NOT NULL,
  `IdPlan` INT NOT NULL,
  `IdTarjeta` INT NOT NULL,
  PRIMARY KEY (`IdPago`),
  CONSTRAINT `fk_Pago_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `mydb`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago_Plan1`
    FOREIGN KEY (`IdPlan`)
    REFERENCES `mydb`.`Plan` (`IdPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago_Tarjeta1`
    FOREIGN KEY (`IdTarjeta`)
    REFERENCES `mydb`.`Tarjeta` (`IdTarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pago_Usuario1_idx` ON `mydb`.`Pago` (`IdUsuario` ASC) VISIBLE;

CREATE INDEX `fk_Pago_Plan1_idx` ON `mydb`.`Pago` (`IdPlan` ASC) VISIBLE;

CREATE INDEX `fk_Pago_Tarjeta1_idx` ON `mydb`.`Pago` (`IdTarjeta` ASC) VISIBLE;

INSERT INTO mydb.Pago (IdPago, Fecha_pago, Monto, IdUsuario, IdPlan, IdTarjeta)
VALUES ('1', '2025-05-22', 299.99, 1, 1, 1);


-- -----------------------------------------------------
-- Table `mydb`.`Notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notificacion` (
  `IdNotificacion` INT NOT NULL AUTO_INCREMENT,
  `Mensaje` TEXT NOT NULL,
  `Fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdNotificacion`))
ENGINE = InnoDB;

INSERT INTO mydb.Notificacion (IdNotificacion, Mensaje)
VALUES ('1', 'Por dia festivo se cerraran las sucursales hasta nuevo aviso.');


-- -----------------------------------------------------
-- Table `mydb`.`Notificacion_Enviada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Notificacion_Enviada` (
  `IdUsuario` INT NOT NULL,
  `IdNotificacion` INT NOT NULL,
  `Leido` TINYINT NOT NULL DEFAULT 0,
  `Fecha_Venc` DATE NOT NULL,
  CONSTRAINT `fk_Usuario_has_Notificacion_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `mydb`.`Usuario` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Notificacion_Notificacion1`
    FOREIGN KEY (`IdNotificacion`)
    REFERENCES `mydb`.`Notificacion` (`IdNotificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_has_Notificacion_Notificacion1_idx` ON `mydb`.`Notificacion_Enviada` (`IdNotificacion` ASC) VISIBLE;

CREATE INDEX `fk_Usuario_has_Notificacion_Usuario1_idx` ON `mydb`.`Notificacion_Enviada` (`IdUsuario` ASC) VISIBLE;

INSERT INTO mydb.Notificacion_Enviada (IdUsuario, IdNotificacion, Leido, Fecha_Venc)
VALUES (1, 1, 0, '2025-06-01');


-- -----------------------------------------------------
-- Table `mydb`.`Ventajas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventajas` (
  `idVentajas` INT NOT NULL AUTO_INCREMENT,
  `Ventajas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVentajas`))
ENGINE = InnoDB;

INSERT INTO mydb.Ventajas (Ventajas)
VALUES
('Acceso ilimitado a contenido premium'),
('Soporte técnico 24/7'),
('Descuentos exclusivos en productos'),
('Acceso a eventos especiales'),
('Contenido sin publicidad'),
('Posibilidad de múltiples dispositivos'),
('Actualizaciones y mejoras gratuitas');


-- -----------------------------------------------------
-- Table `mydb`.`VentajasDelPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VentajasDelPlan` (
  `IdPlan` INT NOT NULL,
  `IdVentajas` INT NOT NULL,
  PRIMARY KEY (`IdPlan`, `IdVentajas`),
  CONSTRAINT `fk_Plan_has_Ventajas_Plan1`
    FOREIGN KEY (`IdPlan`)
    REFERENCES `mydb`.`Plan` (`IdPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plan_has_Ventajas_Ventajas1`
    FOREIGN KEY (`IdVentajas`)
    REFERENCES `mydb`.`Ventajas` (`idVentajas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Plan_has_Ventajas_Ventajas1_idx` ON `mydb`.`VentajasDelPlan` (`IdVentajas` ASC) VISIBLE;

CREATE INDEX `fk_Plan_has_Ventajas_Plan1_idx` ON `mydb`.`VentajasDelPlan` (`IdPlan` ASC) VISIBLE;

INSERT INTO mydb.VentajasDelPlan (IdPlan, IdVentajas)
VALUES
(1, 1),
(1, 3);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
